os: linux
language: rust
rust:
        - nightly
cache: cargo
script:
        - touch Rocket.toml
        - printf "[global.databases]\npostgres_database = { url = \"postgres://postgres:postgres@db/postgres\" }" > Rocket.toml
        - mv src/secret.key.sample src/secret.key
        - cargo build --release
deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        file: "/target/release/address_book_rest_api"
        skip_cleanup: true
        on:
                tags: true
