os: linux
language: rust
rust:
        - nightly
cache: cargo
script:
        - touch Rocket.toml
        - printf "[global.databases]\npostgres_database = { url = \"postgres://postgres:postgres@db/postgres\" }" > Rocket.toml
        - mv src/secret.key.sample src/secret.key
        - cargo build --release
        - mkdir bin
        - cp target/release/address_book_rest_api bin
deploy:
        provider: s3
        access_key_id: "$S3_ACCESS_KEY_ID"
        secret_access_key: "$S3_SECRET_ACCESS_KEY"
        bucket: "address-book-bin"
        region: ap-southeast-1
        acl: public_read
        local-dir: bin
        skip_cleanup: true
