version: '3'
services:
  db:
    container_name: address_book_db
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=postgres
  app:
    container_name: address_book_be
    image: sakadream/rocket-rest-api-with-jwt
    restart: always
    ports:
    - "8000:8000"
    depends_on:
    - db
