pub const MESSAGE_OK: &str = "ok";
pub const MESSAGE_CAN_NOT_INSERT_DATA: &str = "can not insert data";
pub const MESSAGE_CAN_NOT_UPDATE_DATA: &str = "can not update data";
pub const MESSAGE_CAN_NOT_DELETE_DATA: &str = "can not delete data";
pub const MESSAGE_SIGNUP_SUCCESS: &str = "signup successfully";
pub const MESSAGE_SIGNUP_FAILED: &str = "error when signing up, please try again";
pub const MESSAGE_LOGIN_SUCCESS: &str = "login successfully";
pub const MESSAGE_LOGIN_FAILED: &str = "wrong username or password, please try again";
pub const MESSAGE_INVALID_TOKEN: &str = "invalid token, please login again";
